on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Login via Azure Docker Registry'
          uses: azure/docker-login@v1
          with:
            login-server: mangobotregistry2.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - name: 'Docker build and push'
          run: |
            docker build . -t mangobotregistry2.azurecr.io/mangobot:${{ github.sha }}
            docker push mangobotregistry2.azurecr.io/mangobot:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: mangobot
            dns-name-label: mangobot-${{ github.sha }}
            image: mangobotregistry2.azurecr.io/mangobot:${{ github.sha }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: mangobot-aci
            location: 'east us'
            cpu: 1
            memory: 1
            secure-environment-variables: >
              ConnectionStrings__Cosmos=${{ secrets.COSMOS_CONNECTION_STRING }} 
              Discord__Token=${{ secrets.DISCORD_TOKEN }}
              Discord__OpenAiKey=${{ secrets.OPEN_API_KEY }} 
              Discord__PexelApiKey=${{ secrets.PEXEL_API_KEY }}